export const TRANSACTION_ROW_HEIGHT = 48;
export const DAY_HEADER_HEIGHT = 32;
export const NAVBAR_HEIGHT = 72;
export const FILTERS_HEIGHT = 44;
export const PAGE_SIZE = 50;

export const DEFAULT_DATE_RANGE = {
  startDate: new Date(new Date().setDate(1)),
  endDate: new Date(),
};

export const TRANSFER_CATEGORIES = [
  {
    name: "Transfer in",
    icon: "arrow-up-from-line",
    id: process.env.NEXT_PUBLIC_TRANSFER_CATEGORY_IN_ID!,
    type: "transfer",
    user_id: null,
    is_obligation: false,
    keywords: null,
  },
  {
    name: "Transfer out",
    icon: "arrow-down-from-line",
    id: process.env.NEXT_PUBLIC_TRANSFER_CATEGORY_OUT_ID!,
    type: "transfer",
    user_id: null,
    is_obligation: false,
    keywords: null,
  },
  {
    name: "Between wallets",
    icon: "arrow-right-left",
    id: process.env.NEXT_PUBLIC_TRANSFER_CATEGORY_BETWEEN_ID!,
    type: "transfer",
    user_id: null,
    is_obligation: false,
    keywords: null,
  },
];

export const ICONS = [
  "activity",
  "airplay",
  "alarm-clock",
  "ambulance",
  "anchor",
  "apple",
  "backpack",
  "bag",
  "bath",
  "battery",
  "bed",
  "bike",
  "book",
  "box",
  "briefcase",
  "brush",
  "bus",
  "cake-slice",
  "cake",
  "camera",
  "car",
  "carrot",
  "cart",
  "cat",
  "chef-hat",
  "church",
  "coffee",
  "compass",
  "dog",
  "donut",
  "egg",
  "film",
  "fish",
  "flower",
  "gamepad",
  "gift",
  "glass-water",
  "globe",
  "graduation-cap",
  "guitar",
  "hammer",
  "headphones",
  "heart",
  "home",
  "hospital",
  "ice-cream-cone",
  "image",
  "key",
  "laptop",
  "leaf",
  "library",
  "lightbulb",
  "luggage",
  "mail",
  "map",
  "microphone",
  "microscope",
  "monitor",
  "mountain",
  "music",
  "paintbrush",
  "palette",
  "parking-meter",
  "paw-print",
  "phone",
  "pizza",
  "plane",
  "plug",
  "printer",
  "radio",
  "road",
  "rocket",
  "shopping-bag",
  "shopping-cart",
  "speaker",
  "sun",
  "tag",
  "taxi",
  "train",
  "tree",
  "truck",
  "tv",
  "umbrella",
  "utensils-crossed",
  "video",
  "wine",
  "air-vent",
  "alarm-smoke",
  "baby",
  "baggage-claim",
  "balloon",
  "banknote",
  "bed-double",
  "bed-single",
  "bell",
  "bicycle",
  "blinds",
  "book-open",
  "bottle",
  "bread",
  "burger",
  "bus-front",
  "candy",
  "car-front",
  "caravan",
  "castle",
  "chair",
  "chef-hat",
  "clapperboard",
  "cocktail",
  "construction",
  "crown",
  "cup-soda",
  "dog",
  "dumbbell",
  "factory",
  "fast-food",
  "forklift",
  "gas-pump",
  "glass-water",
  "glasses",
  "grape",
  "handshake",
  "hard-hat",
  "headset",
  "home",
  "hot-air-balloon",
  "ice-cream-bowl",
  "ice-cream-cone",
  "key",
  "lamp",
  "laptop",
  "lightbulb",
  "luggage",
  "map",
  "martini",
  "microphone",
  "mountain",
  "movie",
  "music",
  "paintbrush",
  "palette",
  "paw-print",
  "pet",
  "phone",
  "piano",
  "pizza",
  "plane-landing",
  "popcorn",
  "post-office",
  "restaurant",
  "rocket",
  "roller-coaster",
  "sailboat",
  "school",
  "scissors",
  "ship",
  "shopping-bag",
  "shopping-basket",
  "skull",
  "sofa",
  "speaker",
  "stadium",
  "star",
  "sunrise",
  "sunset",
  "swimming-pool",
  "tent",
  "theater",
  "ticket",
  "toilet",
  "tools",
  "tooth",
  "train-front",
  "tram-front",
  "trash",
  "tree",
  "trophy",
  "truck",
  "tv",
  "umbrella",
  "utensils",
  "video",
  "wallet",
  "wine",
  "wrench",
];

// Chart color palette - semantic names for common use cases
export const ChartColors = {
  // Primary semantic colors
  income: "#22c55e", // Green - represents positive cash flow
  expense: "#ef4444", // Red - represents spending
  balance: "#3b82f6", // Blue - represents net/balance
  warning: "#f59e0b", // Orange - represents warnings

  // Extended palette for categories, trends, etc.
  palette: {
    rose: "#B8255F",
    red: "#DB4035",
    lightRed: "#FF8D85",
    orange: "#FF9933",
    yellow: "#FAD000",
    lime: "#AFB83B",
    lightGreen: "#7ECC49",
    green: "#299438",
    teal: "#6ACCBC",
    cyan: "#158FAD",
    lightBlue: "#14AAF5",
    sky: "#96C3EB",
    blue: "#4073FF",
    purple: "#884DFF",
    magenta: "#AF38EB",
    gray: "#B8B8B8",
    brown: "#CCAC93",
  },

  // HSL versions for category trends and distributions
  hsl: {
    green: "hsl(142, 76%, 36%)",
    blue: "hsl(221, 83%, 53%)",
    purple: "hsl(262, 83%, 58%)",
    darkPurple: "hsl(291, 64%, 42%)",
    orange: "hsl(24, 70%, 50%)",
    yellow: "hsl(43, 89%, 38%)",
    teal: "hsl(168, 76%, 42%)",
    cyan: "hsl(199, 89%, 48%)",
    pink: "hsl(339, 82%, 52%)",
    lightYellow: "hsl(48, 96%, 53%)",
    lightOrange: "hsl(25, 95%, 53%)",
    red: "hsl(0, 84%, 60%)",
  },
} as const;

// Backwards compatible array export
export const COLORS = [
  "#B8255F",
  "#DB4035",
  "#FF8D85",
  "#FF9933",
  "#FAD000",
  "#AFB83B",
  "#7ECC49",
  "#299438",
  "#6ACCBC",
  "#158FAD",
  "#14AAF5",
  "#96C3EB",
  "#4073FF",
  "#884DFF",
  "#AF38EB",
  "#B8B8B8",
  "#CCAC93",
];
